CREATE TABLE requests (
  dateOfRequest DATETIME PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  txt VARCHAR(255) NOT NULL,
  trans VARCHAR(255) NOT NULL,
  FOREIGN KEY(username) REFERENCES users(login) ON DELETE CASCADE ON UPDATE CASCADE
);